- hosts: all
  tasks:
  - name: Installing httpd
    package:
      name: "httpd"
      state: present
  - name: Copying webpages to the html directory
    copy:
      src: "/path/to/your/file"
      dest: "/var/www/html/index.html"
  - name: Starting and enabling the httpd service
    service:
      name: "httpd"
      state: restarted
  - name: Adding an exception in firewall for httpd
    ansible.posix.firewalld:
      port: 80/tcp
      state: enabled
      permanent: yes
      immediate: yes